Repository unitaryfoundation/mitiq, pull requests merged in 2022-06, with the labels that each got.

#1319 Add references for DDD theory section
  docs/source/guide/ddd-5-theory.myst
  docs/source/refs.bib
Labels: documentation

#1322 Ensure lists are properly displayed
  docs/source/release.rst
Labels: documentation

#1320 Clean up contributing-to-docs doc
  docs/CONTRIBUTING_DOCS.md
Labels: documentation

#1296 [unitaryhack] Updated molecular hydrogen tutorial
  AUTHORS
  dev_requirements.txt
  docs/source/examples/maxcut-demo.myst
  docs/source/examples/molecular_hydrogen.myst
Labels: unitaryhack-accepted

#1338 [unitaryhack] Add thumbnails for examples
  AUTHORS
  docs/source/_thumbnails/ibmq-gate-map.png
  docs/source/_thumbnails/max-cut.png
  docs/source/_thumbnails/mirror-circuits.png
  docs/source/_thumbnails/mitiq-codeblocks.png
  docs/source/_thumbnails/molecular-hydrogen-vqe.png
  docs/source/_thumbnails/pyquil-demo.png
  docs/source/_thumbnails/simple-landscape.png
  docs/source/_thumbnails/vqe-cirq-pauli-sum-mitigation-plot.png
  docs/source/_thumbnails/vqe-pyquil-demo.png
  docs/source/conf.py
Labels: documentation

#1348 Test on windows and mac on each PR and add openfermion to dev requirements
  .github/workflows/test-master.yml
  .github/workflows/test.yml
Labels: infrastructure

#1354 Deploy asv benchmark data to web
  .github/workflows/asv.yaml
  .github/workflows/test.yml
  README.md
  asv.conf.json
  benchmarks/benchmarks.py
Labels: infrastructure
