Repository unitaryfoundation/mitiq, pull requests merged in 2022-11, with the labels that each got.

#1580 use python 3.10 for asv
  asv.conf.json
Labels: infrastructure, tech debt

#1587 color output from pytest on CI
  pyproject.toml
Labels: infrastructure

#1592 use `\prod` instead of `\Pi`
  docs/source/guide/pec-5-theory.myst
Labels: documentation

#1586 Raise error when inserting DDD sequence with midcircuit measurement
  mitiq/ddd/insertion.py
  mitiq/ddd/tests/test_insertion.py
Labels: ddd

#1603 Techniques intro
  docs/source/examples/simple-landscape-cirq.myst
  docs/source/guide/cdr-1-intro.myst
  docs/source/guide/cdr.myst
  docs/source/guide/ddd-1-intro.myst
  docs/source/guide/ddd.myst
  docs/source/guide/pec-1-intro.myst
  docs/source/guide/pec.myst
  docs/source/guide/zne-1-intro.myst
  docs/source/guide/zne.myst
Labels: documentation
