Repository unitaryfoundation/mitiq, pull requests merged in 2023-12, with the labels that each got.

#2104 Organize API-doc
  docs/source/apidoc.md
Labels: documentation

#2127 resolve flaky mirror QV circuit test
  mitiq/benchmarks/mirror_qv_circuits.py
  mitiq/benchmarks/tests/test_mirror_qv_circuits.py
Labels: benchmarks

#2126 Speed up tests using mocks
  docs/source/guide/calibrators.md
  mitiq/__init__.py
  mitiq/calibration/__init__.py
  mitiq/calibration/calibrator.py
  mitiq/calibration/settings.py
  mitiq/calibration/tests/test_calibration.py
  mitiq/calibration/tests/test_settings.py
  mitiq/qse/qse_utils.py
  mitiq/qse/tests/test_qse.py
Labels: infrastructure

#2124 Frontend/Backend docs clean up
  docs/source/examples/cirq-ibmq-backends.md
  docs/source/examples/ddd_tutorial.md
  docs/source/examples/ggi_summer_school_solved.md
  docs/source/examples/ggi_summer_school_unsolved.md
  docs/source/examples/hamiltonians.md
  docs/source/examples/ibmq-backends.md
  docs/source/examples/learning-depolarizing-noise.md
  docs/source/examples/maxcut-demo.md
  docs/source/examples/molecular_hydrogen.md
  docs/source/examples/pec_tutorial.md
  docs/source/examples/pennylane-ibmq-backends.md
  docs/source/examples/rshadows_tutorial.md
  docs/source/examples/shadows_tutorial.md
  docs/source/examples/simple-landscape-cirq.md
  docs/source/examples/simple-landscape-pennylane.md
  docs/source/examples/simple-landscape-qiskit.md
  docs/source/examples/zne-braket-ionq.md
  docs/source/guide/cdr-1-intro.md
  docs/source/guide/cdr-2-use-case.md
  docs/source/guide/cdr-3-options.md
  docs/source/guide/cdr-4-low-level.md
  docs/source/guide/cdr-5-theory.md
  docs/source/guide/ddd-1-intro.md
  docs/source/guide/ddd-2-use-case.md
  docs/source/guide/ddd-3-options.md
  docs/source/guide/ddd-4-low-level.md
  docs/source/guide/ddd-5-theory.md
  docs/source/guide/executors.md
  docs/source/guide/frontends-backends.md
  docs/source/guide/glossary.md
  docs/source/guide/observables.md
  docs/source/guide/pec-1-intro.md
  docs/source/guide/pec-2-use-case.md
  docs/source/guide/pec-3-options.md
  docs/source/guide/pec-4-low-level.md
  docs/source/guide/pec-5-theory.md
  docs/source/guide/pt-1-intro.md
  docs/source/guide/pt-2-use-case.md
  docs/source/guide/pt-3-options.md
  docs/source/guide/pt-4-low-level.md
  docs/source/guide/pt-5-theory.md
  docs/source/guide/rem-1-intro.md
  docs/source/guide/rem-2-use-case.md
  docs/source/guide/rem-3-options.md
  docs/source/guide/rem-4-low-level.md
  docs/source/guide/rem-5-theory.md
  docs/source/guide/shadows-1-intro.md
  docs/source/guide/shadows-5-theory.md
  docs/source/guide/shadows.md
  docs/source/guide/zne-1-intro.md
  docs/source/guide/zne-2-use-case.md
  docs/source/guide/zne-3-options.md
  docs/source/guide/zne-4-low-level.md
  docs/source/guide/zne-5-theory.md
Labels: documentation

#2130 Clarify CDR training docs regarding the use of a markov chain monte carlo
  docs/source/guide/cdr-1-intro.md
  docs/source/guide/cdr-2-use-case.md
  docs/source/guide/cdr-3-options.md
  docs/source/guide/cdr-4-low-level.md
  docs/source/guide/cdr-5-theory.md
  docs/source/guide/cdr.md
Labels: documentation, cdr
