Repository unitaryfoundation/mitiq, pull requests merged in 2023-05, with the labels that each got.

#1827 clean up sidebar
  docs/source/examples/learning-depolarizing-noise.md
  docs/source/guide/cdr.md
  docs/source/guide/ddd.md
  docs/source/guide/glossary.md
  docs/source/guide/pec.md
  docs/source/guide/rem.md
  docs/source/guide/zne.md
Labels: documentation

#1814 Supports observable multiplication with observable and PauliString
  AUTHORS
  mitiq/observable/observable.py
  mitiq/observable/pauli.py
  mitiq/observable/tests/test_observable.py
  mitiq/observable/tests/test_pauli.py
  mitiq/utils.py
Labels: observable, qse

#1834 add unitaryHACK banner to docs
  docs/source/conf.py
Labels: documentation

#1854 Update GitHub link
  docs/source/_templates/layout.html
  docs/source/conf.py
Labels: bug, documentation, tech debt
