Repository unitaryfoundation/mitiq, pull requests merged in 2023-04, with the labels that each got.

#1663 Uprade python support to 3.11
  .github/workflows/asv.yaml
  .github/workflows/build.yml
  .github/workflows/publish-pypi.yml
  .github/workflows/publish-testpypi.yml
  asv.conf.json
  docs/source/examples/bqskit.md
  pyproject.toml
  setup.py
Labels: infrastructure

#1791 Remove allcontributors
  .all-contributorsrc
  README.md
  docs/source/release.md
Labels: infrastructure

#1803 use 1.7.0 link for grove
  docs/source/examples/vqe-pyquil-demo.ipynb
Labels: documentation

#1767 Support noise scaling by layer
  docs/source/apidoc.md
  docs/source/guide/zne-3-options.md
  docs/source/refs.bib
  mitiq/zne/scaling/__init__.py
  mitiq/zne/scaling/layer_scaling.py
  mitiq/zne/scaling/tests/test_folding.py
  mitiq/zne/scaling/tests/test_layer_scaling.py
  mitiq/zne/tests/test_zne.py
Labels: feature-request
