Repository unitaryfoundation/mitiq, pull requests merged in 2023-10, with the labels that each got.

#2028 New QEM benchmarking method: "rotated" RB circuits
  docs/source/apidoc.md
  docs/source/conf.py
  mitiq/benchmarks/__init__.py
  mitiq/benchmarks/randomized_benchmarking.py
  mitiq/benchmarks/rotated_randomized_benchmarking.py
  mitiq/benchmarks/tests/test_rotated_randomized_benchmarking.py
Labels: benchmarks

#2038 Include calculated error in calibrator logs
  AUTHORS
  mitiq/calibration/calibrator.py
  mitiq/calibration/tests/test_calibration.py
Labels: calibration

#2068 Drop support for python 3.8
  .github/workflows/build.yml
  CONTRIBUTING.md
  docs/source/conf.py
  setup.py
Labels: infrastructure

#2071 Remove "binder" remnants
  binder/requirements.txt
Labels: infrastructure, tech debt

#2069 Clean up GitHub CI
  .github/workflows/build.yml
Labels: infrastructure
