Repository unitaryfoundation/mitiq, pull requests merged in 2024-04, with the labels that each got.

#2277 Retry linkcheck when building docs
  docs/source/conf.py
Labels: documentation

#2279 Use Jupyter cache in gh workflow docs build
  .github/workflows/build.yml
Labels: documentation, infrastructure

#2309 Remove qibo snippet from changelog
  CHANGELOG.md
Labels: documentation, interface-and-conversions

#2269 Upgrade Qiskit to 1.0.2
  dev_requirements.txt
  docs/source/examples/calibration-tutorial.md
  docs/source/examples/cirq-ibmq-backends.md
  docs/source/examples/ddd_on_ibmq_ghz.md
  docs/source/examples/ggi_summer_school_solved.md
  docs/source/examples/ggi_summer_school_unsolved.md
  docs/source/examples/ibmq-backends.md
  docs/source/examples/layerwise-folding.md
  docs/source/examples/mitiq-paper/mitiq-paper-codeblocks.md
  docs/source/examples/pec_tutorial.md
  docs/source/examples/pennylane-ibmq-backends.md
  docs/source/examples/quantum_simulation_scars_ibmq.md
  docs/source/examples/simple-landscape-braket.md
  docs/source/examples/simple-landscape-qiskit.md
  mitiq/ddd/tests/test_insertion.py
  mitiq/interface/conversions.py
  mitiq/interface/mitiq_qiskit/__init__.py
  mitiq/interface/mitiq_qiskit/conversions.py
  mitiq/interface/mitiq_qiskit/qiskit_utils.py
  mitiq/interface/mitiq_qiskit/tests/test_conversions_qiskit.py
  mitiq/interface/mitiq_qiskit/tests/test_qiskit_utils.py
  mitiq/interface/mitiq_qiskit/tests/test_transpiler.py
  mitiq/interface/mitiq_qiskit/transpiler.py
  mitiq/pec/tests/test_pec_sampling.py
  mitiq/pec/types/tests/test_types.py
  mitiq/tests/test_conversions.py
  mitiq/zne/scaling/tests/test_folding.py
  mitiq/zne/tests/test_zne.py
Labels: priority/high, interface-and-conversions
