Repository unitaryfoundation/mitiq, pull requests merged in 2024-06, with the labels that each got.

#2066 Support python 3.12 and drop 3.9
  .github/workflows/build.yml
  .github/workflows/publish-pypi.yml
  .github/workflows/publish-testpypi.yml
  .readthedocs.yml
  CONTRIBUTING.md
  pyproject.toml
  requirements/requirements-pennylane.txt
  setup.py
Labels: infrastructure, monitor-for-external-solution

#2320 Used trusted publishers for testpypi publishing
  .github/workflows/publish-testpypi.yml
  Makefile
  docs/source/release.md
Labels: infrastructure

#2425 bump min python version for intersphinx map
  docs/source/conf.py
Labels: infrastructure

#2421 Update readme
  README.md
Labels: documentation
