Repository unitaryfoundation/mitiq, pull requests merged in 2024-03, with the labels that each got.

#2221 Pin Qibo version
  dev_requirements.txt
Labels: dependencies

#2232 fix pennylane tutorial
  README.md
  docs/source/examples/maxcut-demo.md
  docs/source/examples/pennylane-ibmq-backends.md
  docs/source/examples/simple-landscape-pennylane.md
  mitiq/benchmarks/quantum_volume_circuits.py
Labels: bug, documentation

#2231 Use python 3.11 on RTD
  .readthedocs.yml
Labels: documentation, tech debt

#2234 Add GitHub Discussions to contributing guide
  CONTRIBUTING.md
Labels: documentation

#2242 Fix examples link in README.md
  AUTHORS
  CHANGELOG.md
  README.md
Labels: documentation, non-quantum
